# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhCheckproxy < Formula
  desc "GitHub Checks API proxy for fine-grained personal access tokens"
  homepage "https://github.com/bycli/gh-checkproxy"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bycli/gh-checkproxy/releases/download/v0.1.7/gh-checkproxy_darwin_amd64.tar.gz"
      sha256 "d9b4a685bc7bdcf0127e585a3c16c451681e75bba616be54315959e22786a43f"

      define_method(:install) do
        bin.install "gh-checkproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bycli/gh-checkproxy/releases/download/v0.1.7/gh-checkproxy_darwin_arm64.tar.gz"
      sha256 "e9206870fcfd06857d2c1700719b48429240715a1896b4b5027ed1e551b56a84"

      define_method(:install) do
        bin.install "gh-checkproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bycli/gh-checkproxy/releases/download/v0.1.7/gh-checkproxy_linux_amd64.tar.gz"
      sha256 "88eae52a989997f820a0fa030f108b0d3720988e7ee59eba9e354ac0948b3d18"
      define_method(:install) do
        bin.install "gh-checkproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bycli/gh-checkproxy/releases/download/v0.1.7/gh-checkproxy_linux_arm64.tar.gz"
      sha256 "8f34fac34f0fc9a9c1dcea4955557c092b4b17c630d0480bee45f796e1c66490"
      define_method(:install) do
        bin.install "gh-checkproxy"
      end
    end
  end

  test do
    system "#{bin}/gh-checkproxy", "--help"
  end
end
